import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ProvidersWrapper from "./ProvidersWrapper";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Savannah infomatics",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/savannah.jpg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProvidersWrapper>
      <html lang="en">
        <body className={poppins.variable}>{children}</body>
      </html>
    </ProvidersWrapper>
  );
}
